// Fill-in-the-blank / open-ended prompts for PromptClash. Keep these short,
// funny, and safe for a mixed-age living room crowd.
module.exports = [
	"The worst possible name for a pet rock.",
	"A terrible excuse for being late to your own wedding.",
	"The next big fitness trend that should absolutely not catch on.",
	"What you'd find if you Googled your houseplant's search history.",
	"The real reason dinosaurs went extinct.",
	"A rejected slogan for the city's tourism board.",
	"The worst superpower to have during a job interview.",
	"What robots will complain about once they take over.",
	"The title of your autobiography, if you're being brutally honest.",
	"A bad idea for a new Olympic sport.",
	"The worst thing to hear your pilot say mid-flight.",
	"What aliens would think is our strangest tradition.",
	"A terrible pickup line that somehow works.",
	"The worst name for a boat.",
	"What your GPS says when it's given up on you.",
	"The least convincing superhero origin story.",
	"A bad theme for a children's birthday party.",
	"What you'd yell if you won the world's smallest lottery.",
	"The worst possible fortune cookie message.",
	"A questionable item to bring to a job interview.",
	"The real reason the chicken crossed the road.",
	"What your cat is actually thinking about you.",
	"A terrible name for a new energy drink.",
	"The worst advice a grandparent could give.",
	"What they'll say about this generation in 100 years.",
	"The worst thing to say during a moment of silence.",
	"A bad name for a law firm.",
	"What your search history says about you.",
	"The least relaxing spa treatment imaginable.",
	"A terrible slogan for a used car dealership.",
	"The worst way to find out it's your last day at work.",
	"What ghosts actually complain about.",
	"A bad idea for a first date.",
	"The worst possible caption for your school yearbook photo.",
	"What your smart speaker mutters when you leave the room.",
	"The least appetizing flavor of ice cream.",
	"A terrible name for a new dating app.",
	"The worst thing to say in a wedding toast.",
	"What you'd name a support group for people who microwave fish at work.",
	"The most useless invention of all time.",
	"A bad idea for a new reality TV show.",
	"The worst possible name for a new planet.",
	"What your dog would say if it could talk.",
	"A terrible name for a new superhero.",
	"The worst thing to say during a job interview.",
	"What your fridge would say if it could talk.",
	"A bad idea for a new holiday tradition.",
	"The worst possible name for a new restaurant.",
	"What your houseplants would say if they could talk.",
	"A terrible name for a new video game.",
	"The worst thing to say during a first date.",
	"What your car would say if it could talk.",
];
