// Several selectable "card lists" (decks) of categories, each answered with a
// word/phrase starting with the round's secret letter. Original category
// wording (not copied from any commercial card deck).
module.exports = [
  {
    id: "classics",
    name: "Everyday Classics",
    categories: [
      "Something you find in a kitchen",
      "A type of animal",
      "A school subject",
      "Something you'd pack for vacation",
      "A job or occupation",
      "A type of weather",
      "Something round",
      "A piece of clothing",
      "A way to travel",
      "Something you'd find in a garage",
      "A type of sport",
      "A holiday tradition",
    ],
  },
  {
    id: "food",
    name: "Food & Drink",
    categories: [
      "A type of fruit",
      "Something you'd order at a restaurant",
      "A cooking utensil or appliance",
      "A candy or dessert",
      "Something you'd put on a sandwich",
      "A restaurant chain",
      "A type of soup",
      "Something spicy",
      "A drink you'd order at a cafe",
      "A brand of food or drink",
      "Something you'd cook on a grill",
      "A type of cheese",
    ],
  },
  {
    id: "entertainment",
    name: "Movies, Books & Music",
    categories: [
      "A movie genre",
      "A type of musical instrument",
      "A dance move",
      "A type of book",
      "Something found in a theater",
      "A music genre",
      "A famous type of story (fairy tale, mystery, etc.)",
      "A television show genre",
      "A song title",
      "A type of costume",
      "A word that describes a good song",
      "Something you'd see at a concert",
    ],
  },
  {
    id: "house",
    name: "Around the House",
    categories: [
      "Something in the bathroom",
      "Something in the living room",
      "A household chore",
      "Something you plug in",
      "A tool in a toolbox",
      "Something you'd find in a junk drawer",
      "A piece of furniture",
      "Something you clean with",
      "Something in a bedroom",
      "A type of container",
      "Something you'd find in the garage",
      "Something you'd find under the sink",
    ],
  },
  {
    id: "nature",
    name: "Nature & Animals",
    categories: [
      "A type of bird",
      "Something found in the ocean",
      "A farm animal",
      "A type of tree",
      "Something in a garden",
      "An insect",
      "A type of weather event",
      "A nocturnal animal",
      "Something found in a forest",
      "A type of flower",
      "An animal with stripes or spots",
      "Something you'd see in the sky",
    ],
  },
  {
    id: "travel",
    name: "Travel & Places",
    categories: [
      "A country",
      "A city",
      "Something you'd pack in a suitcase",
      "A type of vehicle",
      "A tourist attraction",
      "Something at an airport",
      "A body of water",
      "A type of lodging",
      "Something you'd see on a road trip",
      "A famous type of landmark",
      "A season to travel in",
      "Something you'd bring to the beach",
    ],
  },
  {
    id: "sunday",
    name: "Church Related",
    categories: [
      "A scripture character",
      "Something found in a Church",
      "Something you are grateful for",
      "Good Sunday activities",
      "A name of Christ",
      "A hymn title or line",
      "A commandment",
      "A fruit or gift of the Spirit",
      "A christmas or easter tradition",
      "A lesson or parable from the scriptures",
      "Something you can do to serve others",
      "A book of scripture",
    ],
  },
];
